[project]
name = "fer-dataset"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fer>=25.10.3",
    "hsemotion-onnx>=0.3.1",
    "insightface>=1.0.1",
    "jupyter>=1.1.1",
    "mediapipe>=0.10",
    "numpy>=2.5.1",
    "onnxruntime>=1.28.0",
    "opencv-python>=5.0.0.93",
    "pandas>=3.0.5",
    "pyyaml>=6.0.3",
    "retina-face>=0.0.18",
    "tqdm>=4.70.0",
    "ultralytics>=8.4.108",
]
