video:
  path: data/raw/videos/pesta_babi.mp4
  fps: 2

visualization:
  enabled: true

landmark_analysis:
  enabled: true
  save_format: npy

analysis:
  landmark_comparison:
    enabled: false


output:
  frames: data/intermediate/frames
  faces: data/intermediate/faces

  intermediate_annotations: data/intermediate/annotations.csv

  dataset: data/processed
  processed_annotations: data/processed/annotations.csv

  visualizations: data/intermediate/landmarks
  landmarks_468: data/intermediate/landmarks_468
  landmark_features: data/intermediate/landmark_features.csv

debug:
  enabled: true
  max_frames: 100
